document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const header=document.querySelector('.site-header');const updateHeader=()=>header?.classList.toggle('scrolled',scrollY>18);updateHeader();addEventListener('scroll',updateHeader,{passive:true});
const themeToggle=document.getElementById('themeToggle');if(localStorage.getItem('portfolio-theme')==='light')document.body.classList.add('light');const themeIcon=()=>{if(themeToggle)themeToggle.textContent=document.body.classList.contains('light')?'☾':'☼'};themeIcon();themeToggle?.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('portfolio-theme',document.body.classList.contains('light')?'light':'dark');themeIcon()});
const menuButton=document.getElementById('menuButton'),navLinks=document.getElementById('navLinks');menuButton?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=open?'×':'☰'});navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');if(menuButton)menuButton.textContent='☰'}));
const current=document.body.dataset.page;document.querySelectorAll('[data-page-link]').forEach(a=>{if(a.dataset.pageLink===current){a.classList.add('active');a.setAttribute('aria-current','page')}});
document.querySelectorAll('.media img').forEach(img=>{const fallback=()=>{img.style.display='none';img.closest('.media')?.classList.add('media-missing');img.nextElementSibling?.classList.add('show')};img.addEventListener('error',fallback);if(img.complete&&img.naturalWidth===0)fallback()});
document.querySelectorAll('video[data-default-volume]').forEach(video=>{video.volume=Number(video.dataset.defaultVolume)});
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const obs=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});reveals.forEach(x=>obs.observe(x))}else reveals.forEach(x=>x.classList.add('visible'));
const timeline=document.querySelector('.timeline');if(timeline){const items=[...timeline.querySelectorAll('.timeline-item')],progress=timeline.querySelector('.timeline-progress');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible','active')}),{threshold:.28});items.forEach(x=>io.observe(x))}else items.forEach(x=>x.classList.add('visible','active'));const update=()=>{const r=timeline.getBoundingClientRect(),middle=innerHeight*.55,travel=Math.min(Math.max(middle-r.top,0),r.height);if(progress)progress.style.height=`${travel}px`};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update)}
